insert into AsociacionProfesional
      (Nombre, Direccion, Telefono, Activa, UsuarioCrea, FechaCrea)
values ('Colegio Medico de El Salvador', null, null, 1, current_user, current_timestamp),
       ('Asociación de Ginecología y Obstetricia', null, null, 1, current_user, current_timestamp),
	   ('Sociedad Salvadoreña de Cardiología', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Neumología', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Oftalmología', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Infectología', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Patología', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Pediatría de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Psiquiatría', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Ciencias Neurológicas de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Gastroenterología y Endoscopía Digestiva de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Sociedad de Cirugía Plástica, Estética y Reconstructiva de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Sociedad Médica de Salud Pública de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Sociedad de Médicos Trabajadores del ISSS', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Radiología, Ultrasonografía e Imágenes Diagnósticas', null, null, 1, current_user, current_timestamp),
	   ('Asociación Dermatológica de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Urología de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Hematología', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Médicos Anestesiólogos de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Cirugía General', null, null, 1, current_user, current_timestamp),
	   ('Sociedad Salvadoreña de Reumatología', null, null, 1, current_user, current_timestamp),
	   ('Sociedad Sociedad Salvadoreña de Coloproctología', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Medicina de Rehabilitación', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Otorrinolaringología, Broncoesofagología y Cirugía de Cabeza y Cuello de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Nefrología e Hipertensión Arterial de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Médicas Salvadoreñas', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Ortopedia y Traumatología', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Medicina Interna', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Neurocirugía de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Médicos Retirados', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Médicos de Sonsonate', null, null, 1, current_user, current_timestamp),
	   ('Asociación Médica de Oriente', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Endocrinología, Diabetes y Nutrición', null, null, 1, current_user, current_timestamp),
	   ('Sociedad Salvadoreña de Endoscopía Ginecológica y Medicina de la Reproducción', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Médicos Escritores', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Médicos del Hospital Rosales', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Alergia, Asma, e Inmunología Clínica', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Medicina Crítica y Cuidados Intensivos', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Neonatologia de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Medicina Crítica y Cuidados Intensivos', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Médicos Anestesiólogos de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Ciencias Neurológicas de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Médicos Infectólogos', null, null, 1, current_user, current_timestamp),
	   ('Asociación Salvadoreña de Otorrinolaringología y Cirugía de Cabeza y Cuello', null, null, 1, current_user, current_timestamp),
	   ('Asociación de Reumatología de El Salvador', null, null, 1, current_user, current_timestamp),
	   ('Sociedad Latinoamericana de Oncología Pediátrica', null, null, 1, current_user, current_timestamp),
	   ('Asociación Médica Latinoamericana de Rehabilitación', null, null, 1, current_user, current_timestamp),
	   ('Sociedad Americana de Oncología Clínica', null, null, 1, current_user, current_timestamp),
	   ('Sociedad Latinoamericana de Alergia, Asma e Inmunología', null, null, 1, current_user, current_timestamp),
	   ('Confederación Iberoamericana de Medicina Familiar y Comunitaria', null, null, 1, current_user, current_timestamp),
	   ('Asociación Médica Mundial', null, null, 1, current_user, current_timestamp),
	   ('Sociedad Latinoamericana de Medicina Interna', null, null, 1, current_user, current_timestamp),
	   ('Asociación Nacional de Enfermeras de El Salvador', null, null, 1, current_user, current_timestamp)
go