-- examenes fisicos
insert into Examen 
       (Nombre, Categoria, Comentario, Activo, FechaCrea, UsuarioCrea)
values ('Inspección', 'EX001', null, 1, current_timestamp, 'Admin'),
       ('Palpación', 'EX001', null, 1, current_timestamp, 'Admin'),
	   ('Percusión', 'EX001', null, 1, current_timestamp, 'Admin'),
	   ('Auscultación', 'EX001', null, 1, current_timestamp, 'Admin')
go
-- examenes de laboratorio
insert into Examen 
       (Nombre, Categoria, Comentario, Activo, FechaCrea, UsuarioCrea)
values ('Sangre', 'EX002', null, 1, current_timestamp, 'Admin'),
       ('Orina', 'EX002', null, 1, current_timestamp, 'Admin'),
	   ('Heces', 'EX002', null, 1, current_timestamp, 'Admin'),
	   ('Tejidos Corporales', 'EX002', null, 1, current_timestamp, 'Admin'),
	   ('Pruebas Genéticas', 'EX002', null, 1, current_timestamp, 'Admin')
go
-- pruebas medicas
insert into Examen 
       (Nombre, Categoria, Comentario, Activo, FechaCrea, UsuarioCrea)
values ('Análisis del Líquido Amniótico (Amniocentesis)', 'EX003', 'La amniocentesis es una prueba de diagnóstico, es decir, indica si el bebé tiene un problema de salud específico', 1, current_timestamp, 'Admin'),
       ('Amplitud de Distribución Eritrocitaria', 'EX003', 'Otros nombres: Prueba RDW-SD (desviación estándar), ancho de distribución de los eritrocitos, distribución de eritrocitos', 1, current_timestamp, 'Admin'),
	   ('Análisis de Cálculos Renales', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Análisis de Globulinas', 'EX003', 'Otros nombres:  Electroforesis de globulinas en suero, examen de proteína total', 1, current_timestamp, 'Admin'),
	   ('Análisis de Hemoglobina', 'EX003', 'Otros nombres: Hb, Hgb', 1, current_timestamp, 'Admin'),
	   ('Análisis de Sangre de la Brecha Aniónica', 'EX003', 'Otros nombres: brecha aniónica sérica, desequilibrio aniónico, diferencia aniónica, hiato aniónico', 1, current_timestamp, 'Admin'),
	   ('Análisis de Sangre de Lipoproteína (a)', 'EX003', 'Otros nombres: Colesterol Lp(a), Lp(a)', 1, current_timestamp, 'Admin'),
	   ('Análisis de Semen', 'EX003', 'Otros nombres: recuento espermático, análisis de esperma, análisis seminal, prueba de fertilidad masculina, seminograma, espermiograma', 1, current_timestamp, 'Admin'),
	   ('Análisis del Complemento', 'EX003', 'Nombres alternativos: prueba del complemento, proteínas del complemento, antígeno del complemento, actividad del complemento C3, C4, CH50, CH100, C1 C1q, C2', 1, current_timestamp, 'Admin'),
	   ('Análisis del Líquido Cefalorraquídeo', 'EX003', 'Otros nombres: Análisis del líquido cerebroespinal, análisis del líquido cefalorraquídeo', 1, current_timestamp, 'Admin'),
	   ('Análisis del Líquido Pleural', 'EX003', 'Nombres alternativos: aspiración de líquido pleural', 1, current_timestamp, 'Admin'),
	   ('Análisis del Líquido Sinovial', 'EX003', 'Otros nombres: análisis del líquido articular', 1, current_timestamp, 'Admin'),
	   ('Anoscopia', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Anticuerpos Antitiroideos', 'EX003', 'Nombres alternativos: anticuerpos antitiroideos, anticuerpo de peroxidasa tiroidea, TPO, Anti-TPO, inmunoglobulina estimulante de la tiroides', 1, current_timestamp, 'Admin'),
	   ('Biopsia de Piel', 'EX003', 'Otros nombres: biopsia con sacabocados, biopsia por raspado, biopsia excisional, biopsia de cáncer de piel, biopsia de células basales, biopsia de células escamosas, biopsia de melanoma', 1, current_timestamp, 'Admin'),
	   ('Biopsia de Seno', 'EX003', 'Otros nombres: biopsia con aguja gruesa; biopsia con aguja gruesa, seno; aspiración con aguja fina; biopsia por cirugía abierta', 1, current_timestamp, 'Admin'),
	   ('Cadenas Ligeras Libres', 'EX003', 'Nombres alternativos: relación kappa/lambda libre, relación cuantitativa kappa/lambda de cadenas libres en suero, Freelite, cadenas ligeras libres de inmunoglobulina', 1, current_timestamp, 'Admin'),
	   ('Cociente de Microalbúmina y Creatinina', 'EX003', 'Otros nombres: proporción de albúmina-creatinina; albúmina en la orina; microalbúmina, orina; ACR (por las siglas en inglés de "Albumin-to-Creatinine Ratio") o UACR', 1, current_timestamp, 'Admin'),
	   ('Conteo de Reticulocitos', 'EX003', 'Nombres alternativos: Recuento retic, porcentaje de reticulocitos, índice de reticulocitos, índice de producción de reticulocitos, IPR', 1, current_timestamp, 'Admin'),
	   ('Conteo Sanguíneo Completo (Hemograma)', 'EX003', 'Otros nombres de un conteo sanguíneo completo: CSC, recuento sanguíneo completo, hemograma', 1, current_timestamp, 'Admin'),
	   ('Creatina Cinasa', 'EX003', 'Nombres alternativos: CK, CK total, creatina fosfocinasa, CPK', 1, current_timestamp, 'Admin'),
	   ('Densitometría Ósea', 'EX003', 'Nombres alternativos: prueba de densidad mineral ósea, prueba DMO, examen DEXA, DXA; absorciometría de rayos X de energía dual', 1, current_timestamp, 'Admin'),
	   ('Diagnóstico Diferencial', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Dióxido de Carbono (CO2) en la sangre', 'EX003', 'Otros nombres: contenido de dióxido de carbono, contenido de CO2, análisis de sangre de dióxido de carbono, concentración de bicarbonato en sangre, bicarbonato en sangre, CO2 total, TCO2, CO2, HCO3', 1, current_timestamp, 'Admin'),
	   ('Ecografía', 'EX003', 'Nombres alternativos: ultrasonido, ultrasonografía, sonografía en el embarazo, ecografía fetal, ecografía obstétrica, sonografía médica diagnóstica, ultrasonido médico diagnóstico', 1, current_timestamp, 'Admin'),
	   ('Ecografía Doppler', 'EX003', 'Nombres alternativos: Ultrasonografia Doppler', 1, current_timestamp, 'Admin'),
	   ('Elastasa Fecal', 'EX003', 'Nombres alternativos: elastasa pancreática, elastasa pancreática fecal, elastasa en heces, FE-1', 1, current_timestamp, 'Admin'),
	   ('Elastografía', 'EX003', 'Nombres alternativos: elastografía hepática, elastografía transitoria, Fibroscan, elastografía RM', 1, current_timestamp, 'Admin'),
	   ('Electrocardiograma', 'EX003', 'Nombres alternativos: EKG', 1, current_timestamp, 'Admin'),
	   ('Electroforesis de Hemoglobina', 'EX003', 'Nombres alternativos: Electroforesis de Hb, evaluación de la hemoglobina, evaluación de hemoglobinopatía, fraccionamiento de la hemoglobina, Hb ELP, análisis de células falciformes', 1, current_timestamp, 'Admin'),
	   ('Electromiografía y Estudios de Conducción Nerviosa', 'EX003', 'Nombres alternativos: estudio electrodiagnóstico, prueba de EMG, electromiograma, velocidad de conducción nerviosa, VCN', 1, current_timestamp, 'Admin'),
	   ('Evaluación de Depresión', 'EX003', 'Nombres alternativos: prueba de depresión', 1, current_timestamp, 'Admin'),
	   ('Evaluación de la Depresión Posparto', 'EX003', 'Nombres alternativos: Escala de depresión posparto de Edimburgo, cuestionario EPDS', 1, current_timestamp, 'Admin'),
	   ('Evaluación de Obesidad', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Evaluación de Quemaduras', 'EX003', 'Nombres alternativos: diagnóstico de una quemadura', 1, current_timestamp, 'Admin'),
	   ('Evaluación de Salud Mental', 'EX003', 'Nombres alternativos: valoración del estado mental, examen de salud mental, evaluación psicológica, prueba psicológica, evaluación psiquiátrica', 1, current_timestamp, 'Admin'),
	   ('Evaluación de Trastornos del Espectro Autista (TEA)', 'EX003', 'Nombres alternativos: Pruebas de TEA', 1, current_timestamp, 'Admin'),
	   ('Evaluación del Riesgo de Caídas', 'EX003', 'Nombres alternativos: evaluación del riesgo de caerse, pruebas del riesgo de caídas, evaluación e intervención', 1, current_timestamp, 'Admin'),
	   ('Evaluación del Riesgo de Suicidio', 'EX003', 'Nombres alternativos: valoración del riesgo de suicidio', 1, current_timestamp, 'Admin'),
	   ('Evaluación del TDAH', 'EX003', 'Nombres alternativos: prueba de TDAH', 1, current_timestamp, 'Admin'),
	   ('Examen de Bilirrubina en Sangre', 'EX003', 'Otros nombres: bilirrubina sérica total, BST', 1, current_timestamp, 'Admin'),
	   ('Examen de Cáncer de Piel', 'EX003', 'Nombres alternativos: inspección de la piel', 1, current_timestamp, 'Admin'),
	   ('Examen de Isoenzimas de la Lactato Deshidrogenasa (LDH)', 'EX003', 'Nombres alternativos: isoenzima LD, isoenzima de la deshidrogenasa láctica', 1, current_timestamp, 'Admin'),
	   ('Examen de la Vista', 'EX003', 'Otros nombres: examen ocular, examen de visión.', 1, current_timestamp, 'Admin'),
	   ('Examen de Nitrógeno Ureico en Sangre (NUS)', 'EX003', 'Otros nombres del examen de nitrógeno ureico en sangre: nitrógeno ureico sanguíneo, NUS, nitrógeno ureico sérico, nitrógeno ureico plasmático', 1, current_timestamp, 'Admin'),
	   ('Examen del Pie Diabético', 'EX003', 'Nombres alternativos: examen completo de los pies', 1, current_timestamp, 'Admin'),
	   ('Examen Dental', 'EX003', 'Nombres alternativos: chequeo dental, examen bucal', 1, current_timestamp, 'Admin'),
	   ('Examen Neurológico', 'EX003', 'Nombres alternativos: exploración neurológica, reconocimiento neurológico', 1, current_timestamp, 'Admin'),
	   ('Fórmula Leucocitaria', 'EX003', 'Otros nombres: Conteo sanguíneo completo (CBC, por sus siglas en inglés) con diferencial, diferencial, recuento diferencial de glóbulos blancos, recuento diferencial de leucocitos', 1, current_timestamp, 'Admin'),
	   ('Fosfatasa Alcalina', 'EX003', 'Otros nombres: FA, ALP (por sus siglas en inglés)', 1, current_timestamp, 'Admin'),
	   ('Frotis de Sangre', 'EX003', 'Otros nombres: frotis de sangre periférica, extensión sanguínea, extensión, análisis de extensión sanguínea', 1, current_timestamp, 'Admin'),
	   ('Glóbulos Blancos en las Heces', 'EX003', 'Nombres alternativos: leucocitos en las heces, conteo de glóbulos blancos en heces, prueba de leucocitos fecales, FLT', 1, current_timestamp, 'Admin'),
	   ('Hematocrito', 'EX003', 'Otros nombres: Hto, hemoglobina y hematocrito', 1, current_timestamp, 'Admin'),
	   ('Hormona Adrenocorticotrópica (ACTH)', 'EX003', 'Nombres alternativos: prueba de ACTH, prueba de corticotropina, hormona adrenocorticotrófica en suero', 1, current_timestamp, 'Admin'),
	   ('Índice de IgG en LCR', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Insulina en la Sangre', 'EX003', 'Nombres alternativos: insulina en ayunas, insulina sérica, insulina total y libre', 1, current_timestamp, 'Admin'),
	   ('Ionograma', 'EX003', 'Nombres alternativos: análisis de electrolitos en suero, sodio (Na), potasio (K), cloro (Cl), dióxido de carbono (CO2)', 1, current_timestamp, 'Admin'),
	   ('Laparoscopia', 'EX003', 'Nombres alternativos: laparoscopia diagnóstica, cirugía laparoscópica', 1, current_timestamp, 'Admin'),
	   ('Marcadores Tumorales', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Monitorización de Fármacos', 'EX003', 'Otros nombres: análisis de niveles de medicamentos, niveles terapéuticos de medicamentos', 1, current_timestamp, 'Admin'),
	   ('Nivel de Acetaminofén', 'EX003', 'Nombres alternativos: prueba de acetaminofén, análisis de acetaminofén en sangre, prueba de paracetamol , prueba de Tylenol', 1, current_timestamp, 'Admin'),
	   ('Nivel de Oxígeno en la sangre', 'EX003', 'Nombres alternativos: análisis de gases sanguíneos, análisis de gases arteriales, análisis de gases de la sangre arterial (GSA), prueba de saturación de oxígeno', 1, current_timestamp, 'Admin'),
	   ('Nivel de Salicilatos', 'EX003', 'Nombres alternativos: prueba del nivel de ácido acetilsalicílico, examen de salicilatos, prueba del nivel de aspirina', 1, current_timestamp, 'Admin'),
	   ('Niveles de Amoníaco', 'EX003', 'Nombres alternativos: prueba de NH3 test, prueba de amoníaco en la sangre, amoníaco en suero, amoníaco en plasma', 1, current_timestamp, 'Admin'),
	   ('Niveles de Colesterol', 'EX003', 'Otros nombres de la prueba de colesterol: perfil de lípidos, panel lípido', 1, current_timestamp, 'Admin'),
	   ('Niveles de Prolactina', 'EX003', 'Nombres alternativos: prueba de PRL test, análisis de sangre de prolactina', 1, current_timestamp, 'Admin'),
	   ('Panel de Patógenos Respiratorios', 'EX003', 'Nombres alternativos: Perfil PR, perfil de virus respiratorios, panel sindrómico', 1, current_timestamp, 'Admin'),
	   ('Panel Metabólico Completo (PMC)', 'EX003', 'Nombres alternativos: chem 14 (en inglés), panel químico, perfil metabólico', 1, current_timestamp, 'Admin'),
	   ('Pielografía Intravenosa (PIV)', 'EX003', 'Nombres alternativos: urografía excretoria', 1, current_timestamp, 'Admin'),
	   ('Prueba de ACE', 'EX003', 'Nombres alternativos: ensayo de ACE, examen de sangre de ACE, prueba de antígeno carcinoembrionario', 1, current_timestamp, 'Admin'),
	   ('Prueba de Ácido Láctico', 'EX003', 'Nombres alternativos: prueba de lactato, ácido láctico en plasma', 1, current_timestamp, 'Admin'),
	   ('Prueba de Ácido Metilmalónico', 'EX003', 'Nombres alternativos: MMA', 1, current_timestamp, 'Admin'),
	   ('Prueba de Ácido Úrico', 'EX003', 'Nombres alternativos: urato sérico, ácido úrico: suero y orina', 1, current_timestamp, 'Admin'),
	   ('Prueba de ADN Fetal Libre', 'EX003', 'Nombres alternativos: prueba de ADN fetal extracelular, prueba de ADNfe, prueba prenatal no invasiva', 1, current_timestamp, 'Admin'),
	   ('Prueba de AFP (Alfafetoproteína)', 'EX003', 'Otros nombres: AFP materna, AFP en suero materno, prueba de alfafetoproteína en suero materno, prueba de alfafetoproteína sérica materna', 1, current_timestamp, 'Admin'),
	   ('Prueba de Albúmina en la Sangre', 'EX003', 'Otros nombres: ALB', 1, current_timestamp, 'Admin'),
	   ('Prueba de Alcohol en la Sangre', 'EX003', 'Otros nombres: control de alcoholemia en sangre, prueba de etanol, alcohol etílico, contenido de alcohol en sangre', 1, current_timestamp, 'Admin'),
	   ('Prueba de Aldosterona', 'EX003', 'Nombres alternativos: aldosterona en suero, aldosterona en orina, aldosterona urinaria', 1, current_timestamp, 'Admin'),
	   ('Prueba de Alergias', 'EX003', 'Otros nombres: Prueba de alergia IgE, análisis cuantitativo de IgE, Inmunoglobulina E, Total de IgE, IgE específico', 1, current_timestamp, 'Admin'),
	   ('Prueba de Alergias en la Piel', 'EX003', 'Nombres alternativos: prueba cutánea de hipersensibilidad tipo 1, prueba de hipersensibilidad, prueba de escarificación, prueba de alergias con parche, prueba intradérmica', 1, current_timestamp, 'Admin'),
	   ('Prueba de Alfa-1 Antitripsina', 'EX003', 'Nombres alternativos: A1AT, deficiencia de alfa-1-antiproteasa, α1-antitripsina', 1, current_timestamp, 'Admin'),
	   ('Prueba de Amilasa', 'EX003', 'Otros nombres: Examen de amilasa, prueba de amilasa sérica, amilasa en orina', 1, current_timestamp, 'Admin'),
	   ('Prueba de Anticuerpos Antinucleares', 'EX003', 'Otros nombres: pruebas analíticas de anticuerpos antinucleares, anticuerpos antinucleares fluorescentes, ANA, FANA (por sus siglas en inglés)', 1, current_timestamp, 'Admin'),
	   ('Prueba de Anticuerpos Antipéptido Cíclico Citrulinado (anti-CCP)', 'EX003', 'Nombres alternativos: anticuerpo contra el péptido citrulinado cíclico, anticuerpo contra el péptido citrulinado, anticuerpo citrulinado, péptido citrulinado anticíclico, anticuerpo anti-CCP, ACPA', 1, current_timestamp, 'Admin'),
	   ('Prueba de Anticuerpos Contra el Músculo Liso', 'EX003', 'Nombres alternativos: anticuerpo antimúsculo liso, anticuerpo de actina de músculo liso', 1, current_timestamp, 'Admin'),
	   ('Prueba de Anticuerpos Contra los Glóbulos Rojos', 'EX003', 'Otros nombres: prueba de anticuerpos, prueba de antiglobulina indirecta, PAI, prueba de antiglobulina humana indirecta, prueba de Coombs indirecta, detección de anticuerpos eritrocitarios', 1, current_timestamp, 'Admin'),
	   ('Prueba de Anticuerpos Frente al Citoplasma de los Neutrófilos', 'EX003', 'Nombres alternativos: anticuerpos ANCA, cANCA pANCA, anticuerpos citoplasmáticos de neutrófilos, anticuerpos citoplasmáticos antineutrófilos, anticuerpos anticitoplasmáticos', 1, current_timestamp, 'Admin'),
	   ('Prueba de Antígeno de Cáncer 125 (para cáncer de ovario)', 'EX003', 'Nombres alternativos: antígeno cancerígeno 125, antígeno glicoprotéico, antígeno de cáncer de ovario, marcador tumoral CA-125', 1, current_timestamp, 'Admin'),
	   ('Prueba de AST', 'EX003', 'Otros nombres: prueba de TGOS, prueba de transaminasa glutámica-oxaloacética en suero, prueba de aspartato aminotransferasa, prueba de SGOT (por sus siglas en inglés)', 1, current_timestamp, 'Admin'),
	   ('Prueba de BRCA', 'EX003', 'Otros nombres: prueba del gen BRCA, gen BRCA 1, gen BRCA 2, gen de susceptibilidad al cáncer de mama 1, gen de susceptibilidad al cáncer de mama 2', 1, current_timestamp, 'Admin'),
	   ('Prueba de Calcio en la Sangre', 'EX003', 'Otros nombres: calcio total, calcio ionizado', 1, current_timestamp, 'Admin'),
	   ('Prueba de Calcio en Orina', 'EX003', 'Otros nombres: análisis de orina (calcio)', 1, current_timestamp, 'Admin'),
	   ('Prueba de Calcitonina', 'EX003', 'Nombres alternativos: tirocalcitonina, CT, calcitonina humana, hCT', 1, current_timestamp, 'Admin'),
	   ('Prueba de Cáncer de Seno HER2', 'EX003', 'Nombres alternativos: receptor 2 del factor de crecimiento epidérmico humano, amplificación ERBB2, sobreexpresión de HER2, análisis HER2/neu', 1, current_timestamp, 'Admin'),
	   ('Prueba de Carga Viral', 'EX003', 'Otros nombres: prueba de ácido nucleico, NAT (por sus siglas en inglés), prueba de amplificación de ácido nucleico, NAAT (por sus siglas en inglés), PCR de VIH, prueba de ARN, cuantificación de VIH', 1, current_timestamp, 'Admin'),
	   ('Prueba de Cariotipo', 'EX003', 'Otros nombres: pruebas genéticas, pruebas cromosómicas, estudios cromosómicos, análisis citogenéticos', 1, current_timestamp, 'Admin'),
	   ('Prueba de CA-19-9 en Sangre (cáncer de páncreas)', 'EX003', 'Nombres alternativos: antígeno de cáncer 19-9, antígeno de carbohidrato 19-9', 1, current_timestamp, 'Admin'),
	   ('Prueba de Ceruloplasmina', 'EX003', 'Nombres alternativos: CP, ceruloplasmina en sangre, ceruloplasmina en suero', 1, current_timestamp, 'Admin'),
	   ('Prueba de Cetonas en la Orina', 'EX003', 'Otros nombres: análisis de cetonas en orina, cetonas urinarias, cuerpos cetónicos, examen de cetonas en orina, prueba de cetonas, prueba de cetonas en orina', 1, current_timestamp, 'Admin'),
	   ('Prueba de Cetonas en Sangre', 'EX003', 'Otros nombres: cuerpos cetónicos en sangre, cetonas séricas, ácido beta-hidroxibutírico, acetoacetato', 1, current_timestamp, 'Admin'),
	   ('Prueba de Clamidia', 'EX003', 'Otros nombres: Prueba NAAT o NAT de clamidia', 1, current_timestamp, 'Admin'),
	   ('Prueba de Cloruro en Sangre', 'EX003', 'Otros nombres: cloruro sérico, prueba de cloruro en suero', 1, current_timestamp, 'Admin'),
	   ('Prueba de Cortisol', 'EX003', 'Otros nombres: cortisol urinario, cortisol salival, cortisol libre, prueba de supresión con dexametasona, DST, prueba de estimulación de ACTH, cortisol en sangre, cortisol plasmático, plasma', 1, current_timestamp, 'Admin'),
	   ('Prueba de Creatinina', 'EX003', 'Nombres alternativos: creatinina en sangre, creatinina en suero, creatinina en orina', 1, current_timestamp, 'Admin'),
	   ('Prueba de Cristales en la Orina', 'EX003', 'Otros nombres: uroanálisis (cristales) análisis de orina microscópico, examen de orina microscópico', 1, current_timestamp, 'Admin'),
	   ('Prueba de Cultivo de Bacterias', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Prueba de Cultivo Fúngico', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Prueba de Detección de Fenilcetonuria (FCU)', 'EX003', 'Nombres alternativos: pruebas de detección para recién nacidos, prueba de PKU (por las siglas en inglés)', 1, current_timestamp, 'Admin'),
	   ('Prueba de Embarazo', 'EX003', 'Nombres alternativos: prueba de gonadotropina coriónica humana, prueba de GCH', 1, current_timestamp, 'Admin'),
	   ('Prueba de Enfermedad Celíaca', 'EX003', 'Nombres alternativos: prueba de anticuerpos de la enfermedad celíaca, anticuerpos contra la transglutaminasa tisular (anticuerpos anti-tTG), anticuerpos anti-gliadina deaminada, anticuerpos antiendomisiales', 1, current_timestamp, 'Admin'),
	   ('Prueba de Estreptococos A', 'EX003', 'Nombres alternativos: prueba de faringitis por estreptococo, cultivo de garganta, cultivo de garganta de estreptococos del grupo A, prueba rápida de estreptococos, Streptococcus pyogenes', 1, current_timestamp, 'Admin'),
	   ('Prueba de Estreptococos del Grupo B', 'EX003', 'Nombres alternativos: estreptococos betahemolíticos del grupo B, streptococcus agalactiae, cultivo de estreptococos betahemolíticos', 1, current_timestamp, 'Admin'),
	   ('Prueba de Estrógeno', 'EX003', 'Otros nombres: prueba de estradiol, estrona (E1), estradiol (E2), estriol (E3), análisis de hormonas estrogénicas', 1, current_timestamp, 'Admin'),
	   ('Prueba de Factor Reumatoideo (FR)', 'EX003', 'Otros nombres: Prueba de sangre de FR', 1, current_timestamp, 'Admin'),
	   ('Prueba de Fosfato en la Orina', 'EX003', 'Otros nombres: prueba de fósforo, P, PO4', 1, current_timestamp, 'Admin'),
	   ('Prueba de Fosfato en la Sangre', 'EX003', 'Otros nombres: prueba de fósforo, P, PO4, fósforo en suero', 1, current_timestamp, 'Admin'),
	   ('Prueba de Gamma-Glutamil Transferasa (GGT)', 'EX003', 'Nombres alternativos: gamma-glutamil transpeptidasa, GGTP, Gamma-GT, GTP', 1, current_timestamp, 'Admin'),
	   ('Prueba de Glucosa en la Orina', 'EX003', 'Otros nombres: examen de azúcar en la orina, examen de glucosa en orina, prueba de glucosuria', 1, current_timestamp, 'Admin'),
	   ('Prueba de Glucosa en la Sangre', 'EX003', 'Otros nombres: azúcar en la sangre, autocontrol de la glucemia, glucosa plasmática en ayunas (GPA), glucemia en ayunas, nivel de azúcar en ayunas, prueba de tolerancia a la glucosa, prueba de tolerancia a la glucosa oral (PTGO)', 1, current_timestamp, 'Admin'),
	   ('Prueba de Gonorrea', 'EX003', 'Otros nombres: cultivo de Neisseria gonorrhoeae, tinción de Gram para N. gonorrhoeae; ADN de N. gonorrhoeae gonorrhea, prueba de amplificación de ácidos nucleicos de la gonorrea (NAAT)', 1, current_timestamp, 'Admin'),
	   ('Prueba de Haptoglobina', 'EX003', 'Otros nombres: proteína de unión a la hemoglobina, HPT, HP', 1, current_timestamp, 'Admin'),
	   ('Prueba de Hemoglobina A1c', 'EX003', 'Otros nombres: HbA1c, A1c, glicohemoglobina, hemoglobina glucosilada, hemoglobina glicosilada', 1, current_timestamp, 'Admin'),
	   ('Prueba de Hepatitis', 'EX003', 'Otros nombres: prueba de hepatitis aguda, prueba de hepatitis vírica, prueba de detección de la hepatitis', 1, current_timestamp, 'Admin'),
	   ('Prueba de Homocisteína', 'EX003', 'Otros nombres: homocisteína total, homocisteína total en plasma', 1, current_timestamp, 'Admin'),
	   ('Prueba de Hormona Paratiroidea (PTH)', 'EX003', 'Nombres alternativos: paratohormona, PTH intacto', 1, current_timestamp, 'Admin'),
	   ('Prueba de Huevos y Parásitos', 'EX003', 'Nombres alternativos: prueba de parásitos y huevos en las heces, prueba de muestra de heces, frotis fecal', 1, current_timestamp, 'Admin'),
	   ('Prueba de Inmunofijación', 'EX003', 'Nombres alternativos: electroforesis de proteínas séricas, SPEP (por sus siglas en inglés), electroforesis de proteínas, SPE (por sus siglas en inglés), electroforesis de inmunofijación, IFE, prueba de inmunofijación sérica', 1, current_timestamp, 'Admin'),
	   ('Prueba de la Fiebre del Dengue', 'EX003', 'Nombres alternativos: anticuerpo del virus del dengue, virus del dengue por PCR', 1, current_timestamp, 'Admin'),
	   ('Prueba de la Gripe (Influenza)', 'EX003', 'Otros nombres: Prueba rápida de la influenza, prueba del antígeno de la gripe, prueba rápida de diagnóstico de la influenza, RIDT (siglas en inglés de "pruebas de diagnóstico rápido de la influenza"), PCR del virus de la gripe', 1, current_timestamp, 'Admin'),
	   ('Prueba de la Hormona Antimulleriana', 'EX003', 'Nombres alternativos: Prueba de la hormona AMH, hormona inhibidora mulleriana, MIH, factor inhibidor mulleriano, MIF, sustancia inhibidora mulleriana, MIS', 1, current_timestamp, 'Admin'),
	   ('Prueba de la Médula Ósea', 'EX003', 'Otros nombres: examen de la médula ósea', 1, current_timestamp, 'Admin'),
	   ('Prueba de Lactato Deshidrogenasa (LDH)', 'EX003', 'Nombres alternativos: prueba de LDH, deshidrogenasa láctica, deshidrogenasa del ácido láctico', 1, current_timestamp, 'Admin'),
	   ('Prueba de Lipasa', 'EX003', 'Otros nombres: lipasa sérica, lipasa en la sangre, LPS', 1, current_timestamp, 'Admin'),
	   ('Prueba de Magnesio en la Sangre', 'EX003', 'Nombres alternativos: Mg, Mag, magnesio en suero', 1, current_timestamp, 'Admin'),
	   ('Prueba de Marcador Tumoral AFP (alfafetoproteína)', 'EX003', 'Nombres alternativos: AFP total, porcentaje de alfafetoproteína-L3', 1, current_timestamp, 'Admin'),
	   ('Prueba de Marcador Tumoral de Microglobulina Beta-2 (B2M)', 'EX003', 'Nombres alternativos: microglobulina β2 total, microglobulina beta-2, B2M', 1, current_timestamp, 'Admin'),
	   ('Prueba de Marcadores Tumorales de Cáncer de Pulmón', 'EX003', 'Otros nombres: pruebas de genes objetivo de cáncer de pulmón', 1, current_timestamp, 'Admin'),
	   ('Prueba de Moco en la Orina', 'EX003', 'Otros nombres: análisis de orina microscópico, examen de orina, prueba de orina, uroanálisis', 1, current_timestamp, 'Admin'),
	   ('Prueba de Mutaciones de MTHFR', 'EX003', 'Otros nombres: homocisteína total en plasma, prueba de la mutación del ADN de la metilentetrahidrofolato reductasa', 1, current_timestamp, 'Admin'),
	   ('Prueba de Nitritos en la Orina', 'EX003', 'Otros nombres: prueba de orina, análisis de orina, análisis de orina microscópico, examen de orina microscópico, UA', 1, current_timestamp, 'Admin'),
	   ('Prueba de Niveles de la Hormona Foliculoestimulante (FSH)', 'EX003', 'Nombres alternativos: folitropina, HFE, hormona foliculoestimulante en suero', 1, current_timestamp, 'Admin'),
	   ('Prueba de Niveles de la Hormona Luteinizante (HL)', 'EX003', 'Nombres alternativos: lutropina, hormona estimulante de las células intersticiales', 1, current_timestamp, 'Admin'),
	   ('Prueba de Niveles de Testosterona', 'EX003', 'Otros nombres: testosterona en suero, testosterona total, testosterona libre, testosterona biodisponible', 1, current_timestamp, 'Admin'),
	   ('Prueba de Papanicolaou', 'EX003', 'Otros nombres de la prueba de Papanicolaou: citología cervical, citología exfoliativa, citología vaginal, frotis de Pap, frotis de Papanicolaou, prueba de Pap', 1, current_timestamp, 'Admin'),
	   ('Prueba de PD-L1 (Inmunoterapia)', 'EX003', 'Nombres alternativos: ligando 1 de muerte programada, PD-LI, PDL-1 por inmunohistoquímica (IHC)', 1, current_timestamp, 'Admin'),
	   ('Prueba de Péptido C', 'EX003', 'Otros nombres: péptido C de insulina, péptido conectivo, péptido C de proinsulina', 1, current_timestamp, 'Admin'),
	   ('Prueba de Potasio en Sangre', 'EX003', 'Otros nombres: potasio en suero, potasio sérico, electrolitos séricos, K', 1, current_timestamp, 'Admin'),
	   ('Prueba de Procalcitonina', 'EX003', 'Otros nombres: Prueba de PCT', 1, current_timestamp, 'Admin'),
	   ('Prueba de Progesterona', 'EX003', 'Nombres alternativos: progesterona sérica, prueba o análisis de sangre de progesterona, PGSN', 1, current_timestamp, 'Admin'),
	   ('Prueba de Proteína C Reactiva (PCR)', 'EX003', 'Otros nombres: proteína c-reactiva, PCR de alta sensibilidad; PCR-as', 1, current_timestamp, 'Admin'),
	   ('Prueba de Proteínas en la Orina', 'EX003', 'Otros nombres: albúmina en la orina, albúmina urinaria, albuminuria, proteína urinaria, proteinuria, prueba de proteína en orina de 24 horas, tira reactiva de uroanálisis', 1, current_timestamp, 'Admin'),
	   ('Prueba de PSA (Antígeno Prostático Específico)', 'EX003', 'Otros nombres: PSA total o PSA libre', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre de ALT', 'EX003', 'Otros nombres: Alanina transaminasa (ALT), SGPT, glutamato piruvato transaminasa en suero, GPT', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre de Ferritina', 'EX003', 'Otros nombres: ferritina sérica, nivel de ferritina sérica, ferritina sérica', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre de Inmunoglobulinas', 'EX003', 'Otros nombres: inmunoglobulinas cuantitativas, inmunoglobulinas totales, IgG, IgM, prueba de IgA', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre de Metales Pesados', 'EX003', 'Otros nombres: panel de metales pesados, metales tóxicos, prueba de toxicidad de metales pesados', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre de Prealbúmina', 'EX003', 'Otros nombres: prealbúmina vinculante de la tiroxina, PA, transtirretina, prueba de transtirretina', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre de SHBG', 'EX003', 'Nombres alternativos: proteína enlazante de estrógenos y testosterona, globulina transportadora de hormonas sexuales, TEBG', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre de VCM', 'EX003', 'Otros nombres: Hemograma completo con fórmula leucocitaria', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre de VPM', 'EX003', 'Volumen plaquetario medio', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre en la Orina', 'EX003', 'Otros nombres: análisis de orina microscópico, examen de orina, prueba de orina, uroanálisis', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sangre oculta en Heces', 'EX003', 'Otros nombres: SOH, sangre oculta en heces, examen de sangre oculta en heces, examen de sangre oculta en materia fecal, prueba de sangre oculta en materia fecal con guayacol, prueba inmunoquímica fecal', 1, current_timestamp, 'Admin'),
	   ('Prueba de Síndrome de Down', 'EX003', 'También llamado trisomía 21', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sodio en la Sangre', 'EX003', 'Otros nombres: Prueba de Na', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sudor', 'EX003', 'Otros nombres: prueba de cloruro en sudor, prueba del sudor para la fibrosis quística, electrolitos en sudor', 1, current_timestamp, 'Admin'),
	   ('Prueba de Sulfato de DHEA', 'EX003', 'Nombres alternativos: DHEA-S, DHEA-SO4, sulfato de dehidroepiandrosterona', 1, current_timestamp, 'Admin'),
	   ('Prueba de Tasa de Filtración Glomerular (TFG)', 'EX003', 'Otros nombres: TFG estimada, tasa de filtración glomerular estimada, tasa de filtración glomerular calculada, TFGc', 1, current_timestamp, 'Admin'),
	   ('Prueba de Tiempo de Protrombina e INR (TP/INR)', 'EX003', 'Nombres alternativos: tiempo de protrombina/índice internacional normalizado; tiempo de coagulación: tiempo de protrombina', 1, current_timestamp, 'Admin'),
	   ('Prueba de Tiroxina (T4)', 'EX003', 'Otros nombres: tiroxina libre, T4 libre, concentración total de T4, análisis de tiroxina, concentración de T4 libre', 1, current_timestamp, 'Admin'),
	   ('Prueba de Tos Ferina', 'EX003', 'Otros nombres: prueba de tos ferina, cultivo de Bordetella pertussis, prueba de tosferina, prueba de tos convulsiva', 1, current_timestamp, 'Admin'),
	   ('Prueba de TPT (Tiempo Parcial de Tromboplastina)', 'EX003', 'Nombres alternativos: tiempo parcial de tromboplastina activado, TPTA', 1, current_timestamp, 'Admin'),
	   ('Prueba de Tricomoniasis', 'EX003', 'Nombres alternativos: T. vaginalis, pruebas de trichomonas vaginalis, preparación en fresco', 1, current_timestamp, 'Admin'),
	   ('Prueba de Triglicéridos', 'EX003', 'Otros nombres de la prueba de triglicéridos: TG, TRIG, perfil lipídico, perfil lipoproteínico en ayunas', 1, current_timestamp, 'Admin'),
	   ('Prueba de Troponina', 'EX003', 'Nombres alternativos: troponina cardíaca I (cTnI), troponina cardíaca T (cTnT), troponina cardíaca (cTN), troponinas cardíacas específicas I y T', 1, current_timestamp, 'Admin'),
	   ('Prueba de TSH', 'EX003', 'Otros nombres: prueba de tirotropina', 1, current_timestamp, 'Admin'),
	   ('Prueba de Tuberculosis', 'EX003', 'Nombres alternativos: prueba de TB, prueba cutánea de TB, prueba de PPD, prueba de IGRA', 1, current_timestamp, 'Admin'),
	   ('Prueba de Uribilinógeno en Orina', 'EX003', 'Otros nombres: prueba de orina, análisis de orina, uroanálisis', 1, current_timestamp, 'Admin'),
	   ('Prueba de Vaginosis Bacteriana', 'EX003', 'Nombres alternativos: prueba de pH vaginal, prueba de hidróxido de potasio (KOH), prueba mediante preparación en fresco', 1, current_timestamp, 'Admin'),
	   ('Prueba de Varicela y Herpes Zóster', 'EX003', 'Nombres alternativos: anticuerpo contra el virus de la varicela-zóster, nivel de anticuerpos de la inmunoglobulina G contra la varicela en suero, anticuerpos IgG e IgM contra el VVZV, herpes zóster', 1, current_timestamp, 'Admin'),
	   ('Prueba de VIH', 'EX003', 'Pruebas de anticuerpos y antígenos del VIH; evaluación de antígenos y anticuerpos del VIH-1 y del VIH-2; prueba de VIH; prueba de anticuerpos contra el virus de la inmunodeficiencia humana tipo 1; prueba del antígeno p24 del VIH', 1, current_timestamp, 'Admin'),
	   ('Prueba de Vitamina B', 'EX003', 'Nombres alternativos: pruebas de vitamina B, complejo vitamínico B, tiamina (B1), riboflavina (B2), niacina (B3), ácido pantoténico (B5), piridoxina (B6), biotina (B7), vitamina B12 y folato', 1, current_timestamp, 'Admin'),
	   ('Prueba de Vitamina D', 'EX003', 'Otros nombres: Calcidiol, calcifediol, hidroxicolecalciferol, 25 (OH) D', 1, current_timestamp, 'Admin'),
	   ('Prueba de Vitamina E (tocoferol)', 'EX003', 'Otros nombres: Prueba de tocoferol, prueba de alfa-tocoferol, prueba de vitamina E en suero', 1, current_timestamp, 'Admin'),
	   ('Prueba del dímero D', 'EX003', 'Nombres alternativos: fragmento de dímero D, fragmento de degradación de fibrina', 1, current_timestamp, 'Admin'),
	   ('Prueba del Trastorno de Pánico', 'EX003', 'Otros nombres: evaluación del trastorno de pánico', 1, current_timestamp, 'Admin'),
	   ('Prueba del Trastorno Obsesivo-Compulsivo (TOC)', 'EX003', 'Nombres alternativos: pruebas de TOC', 1, current_timestamp, 'Admin'),
	   ('Prueba del Virus del Herpes Simple (VHS)', 'EX003', 'Nombres alternativos: cultivo de herpes, cultivo viral del herpes simple, anticuerpos VHS-1, VHS-2, ADN del VHS', 1, current_timestamp, 'Admin'),
	   ('Prueba del Virus del Papiloma Humano (VPH)', 'EX003', 'Nombres alternativos: papilomavirus humano genital, PVH de alto riesgo, prueba de ADN para el PVH, prueba de ARN para el VPH', 1, current_timestamp, 'Admin'),
	   ('Prueba del Virus del Zika', 'EX003', 'Otros nombres: prueba de anticuerpos del Zika, prueba RT-PCR de Zika, prueba Zika', 1, current_timestamp, 'Admin'),
	   ('Prueba del Virus Sincicial Respiratorio (VSR)', 'EX003', 'Otros nombres: prueba de anticuerpos contra el virus sincicial respiratorio, prueba de detección rápida del VSR', 1, current_timestamp, 'Admin'),
	   ('Prueba Genética BCR-ABL', 'EX003', 'Nombres alternativos: BCR-ABL1, fusión de BCR-ABL1, cromosoma Filadelfia', 1, current_timestamp, 'Admin'),
	   ('Prueba Genética del BRAF', 'EX003', 'Nombres alternativos: análisis de la mutación del gen BRAF, melanoma, mutación BRAF V600, Cobas®', 1, current_timestamp, 'Admin'),
	   ('Prueba Genética del PTEN', 'EX003', 'Otros nombres: Gen PTEN, análisis genético completo; secuenciación y eliminación o duplicación del PTEN', 1, current_timestamp, 'Admin'),
	   ('Prueba Genética TP 53 (proteína tumoral 53)', 'EX003', 'Otros nombres: análisis de la mutación TP53, análisis genético completo de la mutación TP53, mutación somática TP53', 1, current_timestamp, 'Admin'),
	   ('Pruebas Cognitivas', 'EX003', 'Nombres alternativos: evaluación cognitiva, Evaluación Cognitiva Montreal, prueba MoCA y en inglés, Mini-Mental State Exam (MMSE) y Mini-Cog', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Alergias Alimentarias', 'EX003', 'Nombres alternativos: prueba de IgE, prueba de tolerancia oral, prueba oral', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Apendicitis', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Pruebas de Audición para Adultos', 'EX003', 'Nombres alternativos: audiometría, audiografía, audiograma, prueba auditiva, prueba de sonido', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Audición para Niños', 'EX003', 'Nombres alternativos: audiometría, audiografía, audiograma, prueba auditiva, prueba de sonido', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Bacilos Acidorresistentes (BAAR)', 'EX003', 'Nombres alternativos: frotis y cultivo de AFB (éstas son las siglas de BAAR en inglés), cultivo y prueba de sensibilidad a la TB, frotis y cultivo de micobacterias', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Bilirrubina en la Orina', 'EX003', 'Otros nombres: prueba de orina, análisis de orina, uroanálisis, bilirrubina directa', 1, current_timestamp, 'Admin'),
	   ('Pruebas de C. Difficile', 'EX003', 'Nombres alternativos: C. difficile; Clostridium difficile; prueba de glutamato deshidrogenasa; Clostridioides difficile, prueba de GDH; prueba de toxina de C. difficile', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Células Epiteliales en la Orina', 'EX003', 'Otros nombres: análisis de orina microscópico, examen de orina, prueba de orina, uroanálisis', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Conmoción Cerebral', 'EX003', 'Nombres alternativos: evaluación de una conmoción cerebral', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Coronavirus', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Pruebas de Drogas', 'EX003','Otros nombres: prueba de detección de drogas, análisis de drogas, prueba de drogas adictivas, prueba de abuso de sustancias, análisis toxicológico, examen toxicológico, control antidoping.', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Esfuerzo', 'EX003', 'Nombres alternativos: ECG de ejercicio, ECG de esfuerzo, ecocardiograma de esfuerzo, ergometría en cinta sin fin, prueba de esfuerzo con ejercicio, prueba de esfuerzo nuclear', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Función Pulmonar', 'EX003', 'Otros nombres: pruebas de funcionamiento pulmonar, PFP', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Glaucoma', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Pruebas de Helicobacter Pylori (H. Pylori)', 'EX003', 'Nombres alternativos: antígeno de H. pylori en heces, pruebas de H. pylori en el aliento, prueba de urea en el aliento, prueba rápida de ureasa para la detección de H. pylori, cultivo de H. pylori', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Hierro', 'EX003', 'Nombres alternativos: Pruebas de Fe, índices de hierro', 1, current_timestamp, 'Admin'),
	   ('Pruebas de la Enfermedad de Lyme', 'EX003', 'Inmunotransferencia (Western blot) para la enfermedad de Lyme, prueba de la enfermedad de Lyme (LCR), anticuerpos Borrelia, IgM/IgG (inmunoglobulina M, inmunoglobulina G), serología para la enfermedad de Lyme, ELISA para la enfermedad de Lyme', 1, current_timestamp, 'Admin'),
	   ('Pruebas de los Factores de la Coagulación', 'EX003', 'Factores de la coagulación sanguínea, pruebas de factores, análisis de factores específicos de la coagulación por número (Factor I, Factor II, Factor VIII, etc.) o por nombre (fibrinógeno, protrombina, hemofilia A, hemofilia B)', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Malaria', 'EX003', 'Nombres alternativos: frotis de sangre de malaria, prueba de diagnóstico rápido de la malaria, diagnóstico de malaria por PCR', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Mononucleosis', 'EX003', 'Nombres alternativos: prueba rápida de la mononucleosis infecciosa, prueba de anticuerpos heterófilos contra el virus de Epstein-Barr, prueba de anticuerpos heterófilos, prueba de anticuerpos contra el VEB', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Opiáceos', 'EX003', 'Nombres alternativos: detección de opioides, detección de opiáceos', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Péptidos Natriuréticos (BNP, NT-proBNP)', 'EX003', 'Nombres alternativos: péptido natriurético cerebral, prueba de pro-péptido natriurético de tipo B, péptido natriurético de tipo B', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Porfirina', 'EX003', 'Protoporfirina; protoporfirinas en sangre; porfirinas en orina; protoporfirinas en heces; uroporfirina; porfirinas; prueba de Mauzerall-Granick; ácido; ALA (ácido aminolevulínico); porfobilinógeno; PBG (por sus siglas en inglés)', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Proteína C y Proteína S', 'EX003', 'Otros nombres: antígeno de la proteína C, antígeno de la proteína S', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Sarampión y Paperas', 'EX003', 'Otros nombres: prueba de inmunidad al sarampión, prueba de inmunidad a las paperas, prueba de sangre de sarampión, cultivo del virus del sarampión, cultivo del virus de las paperas.', 1, current_timestamp, 'Admin'),
	   ('Pruebas de SARM', 'EX003', 'Nombres alternativos: prueba de Staphylococcus aureus meticilinorresistente, prueba de MRSA (siglas de SARM en inglés)', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Sífilis', 'EX003', 'Reagina plasmática rápida (RPR), pruebas del laboratorio de investigación de enfermedades venéreas (VDRL), prueba de absorción de anticuerpos treponémicos fluorescentes (FTA-ABS), ensayo de aglutinación de partículas (TPPA)', 1, current_timestamp, 'Admin'),
	   ('Pruebas de Triyodotironina (T3)', 'EX003', 'Nombres alternativos: prueba de funcionamiento tiroideo; triyodotironina total, triyodotironina libre, FT3', 1, current_timestamp, 'Admin'),
	   ('Pruebas del Equilibrio', 'EX003', 'Nombres alternativos: pruebas vestibulares', 1, current_timestamp, 'Admin'),
	   ('Pruebas Farmacogenéticas', 'EX003', 'Otros nombres: farmacogenómica, pruebas farmacogenómicas', 1, current_timestamp, 'Admin'),
	   ('Pruebas Funcionales Hepáticas', 'EX003', 'Nombres alternativos: pruebas del hígado, panel de función hepática, PFH, exámenes de función hepática, perfil hepático', 1, current_timestamp, 'Admin'),
	   ('Pruebas para Detectar Infecciones por Cándida', 'EX003', 'Otros nombres: preparado de hidróxido de potasio, cultivo fúngico, pruebas de antígenos fúngicos y anticuerpos, tinción blanco de calcoflúor, frotis para hongos', 1, current_timestamp, 'Admin'),
	   ('Pruebas y Bancos de Sangre del Cordón Umbilical', 'EX003', null, 1, current_timestamp, 'Admin'),
	   ('Recuento de Linfocitos CD4', 'EX003', 'Otros nombres: Recuento de linfocitos CD4, recuento de CD4+, recuento de T4, recuento de linfocitos T cooperadores, porcentaje de CD4, conteo de células T', 1, current_timestamp, 'Admin'),
	   ('Tasa de Sedimentación Eritrocítica', 'EX003', 'Otros nombres: ESR, tasa de sedimentación de eritrocitos; tasa de sedimentación de Westergren; VSG, velocidad de sedimentación globular', 1, current_timestamp, 'Admin'),
	   ('Tinción de Gram', 'EX003', 'Nombres alternativos: Coloración de Gram', 1, current_timestamp, 'Admin'),
	   ('Tiroglobulina', 'EX003', 'Nombres alternativos: Tg, TGB. marcador tumoral de tiroglobulina', 1, current_timestamp, 'Admin'),
	   ('Videonistagmografía (VNG)', 'EX003', 'Nombres alternativos: VNG', 1, current_timestamp, 'Admin'),
	   ('17-Hidroxiprogesterona', 'EX003', 'Nombres alternativos: 17-OH progesterona, 17-OHP', 1, current_timestamp, 'Admin')
go


