//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace visible.medico.Expediente.Module.BusinessObjects
{
  [DefaultClassOptions]
  [DevExpress.ExpressApp.DC.XafDisplayNameAttribute("Vacuna Dosis")]
  public partial class VacunaDosis : DevExpress.Xpo.XPObject
  {
    private visible.medico.Expediente.Module.BusinessObjects.Vacuna _vacuna;
    private System.String _comentario;
    private System.String _edad;
    private System.Int16 _dosis;
    public VacunaDosis(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.Int16 Dosis
    {
      get
      {
        return _dosis;
      }
      set
      {
        SetPropertyValue("Dosis", ref _dosis, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(50)]
    public System.String Edad
    {
      get
      {
        return _edad;
      }
      set
      {
        SetPropertyValue("Edad", ref _edad, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(200)]
    public System.String Comentario
    {
      get
      {
        return _comentario;
      }
      set
      {
        SetPropertyValue("Comentario", ref _comentario, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Dosis-Vacuna")]
    public visible.medico.Expediente.Module.BusinessObjects.Vacuna Vacuna
    {
      get
      {
        return _vacuna;
      }
      set
      {
        SetPropertyValue("Vacuna", ref _vacuna, value);
      }
    }
  }
}
