pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./acercade.html","Introducción &#62; Acerca del Sistema","Este documento tiene como propósito describir la funcionalidad del Sistema de Registro Electrónico de Pacientes. Es una herramienta para la admini...",""],
["./agregar-registro.html","Funciones Generales &#62; Agregar Registro","Los pasos generales para agregar un registro en cualquier mantenimiento son los siguientes:",""],
["./borrar-registro.html","Funciones Generales &#62; Borrar Registro","Puede borrar un registro seleccionandolo en la vista lista. Otra alternativa es borrar el registro actual de la vista de detalle. Los pasos generi...",""],
["./buscar-lista-seleccion.html","Funciones Generales &#62; Buscar en Lista de Seleccion","Cuando agrega registros en formularios o los edita, es normal que hallan lista de selección correspondientes a datos relacionados. Por ejemplo, si...",""],
["./citas-medicas.html","Salud &#62; Citas Medicas","Los pasos a sesguir para el registro de las citas médicas son:",""],
["./consulta-medica.html","Salud &#62; Consulta Medica","Para agregar o dar mantenimiento a las Consultas Medicas, puede hacerlo de dos formas:",""],
["./expediente-de-pacientes-agrega.html","Salud &#62; Expediente de Pacientes Agregar","Para agregar un nuevo expediente, seguir los siguientes pasos:",""],
["./expediente-de-pacientes-editar.html","Salud &#62; Expediente de Pacientes Editar","Para Editar un expediente, seguir los siguientes pasos:",""],
["./expediente-pacientes.html","Salud &#62; Expediente de Pacientes","Esta opción permite agregar expedientes de nuevos pacientes, consultar y darles mantenimiento. Además permiten integrar la información que se gene...",""],
["./exportar.html","Funciones Generales &#62; Exportar","Esta función se utiliza para exportar los registros de la vista de Lista de un mantenimiento a diferentes formatos, específicamente cualquiera de ...",""],
["./filtros-y-consultas.html","Funciones Generales &#62; Filtros y Consultas","Los filtros o consultas, se implementan siempre en las vistas de lista. El sistema proporciona al usuario los siguientes mecanismos para hacerlos:",""],
["./guia-inicio-rapida.html","Inicio del Sistema &#62; Guía de Inicio Rápida","Para inicio rápido del sistema después de la instalación, siga los pasos siguientes:",""],
["./ingresosistema1.html","Inicio del Sistema &#62; Ingreso al Sistema","Para cargar la aplicación, su administrador le indicará el enlace que debe ingresar en la barra de direcciones de su navegador favorito. El víncul...",""],
["./mi-cuenta.html","Inicio del Sistema &#62; Mi Cuenta","Al dar clic en este enlace, el sistema muestra el detalle de la cuenta del usuario logeado en el sistema. ",""],
["./mi-detalle.html","Seguridad &#62; Mi Detalle","Esta opción se utiliza para que el usuario logeado (su usuario) conozca a detalle los roles de los cuales es miembro y los permisos que tiene asig...",""],
["./modificar-registro.html","Funciones Generales &#62; Modificar Registro","Los pasos generales para agregar un registro en cualquier mantenimiento son los siguientes:",""],
["./mostrar-y-ocultar-columnas.html","Funciones Generales &#62; Mostrar y Ocultar Columnas","Esta función se utiliza para ocultar o mostrar columnas en la vistas de tipo lista. Para usarla debe:",""],
["./ordenar-registros.html","Funciones Generales &#62; Ordenar Registros","Con esta función se facilita al usuario cambiar el orden en las vistas tipo Lista. Los pasos para usarla son:",""],
["./paginaprincipal.html","Inicio del Sistema &#62; Página Principal","Contiene las funciones comunes de la aplicación y la navegación en el menú de opciones. Solo se muestran en la navegación, las opciones a las cual...",""],
["./panel-agrupar.html","Funciones Generales &#62; Panel Agrupar","Esta función se utiliza para mostrar u ocultar un panel que facilita agrupar los datos mostrados en una vista de tipo lista. Los datos se pueden a...",""],
["./requisitos.html","Introducción &#62; Requisitos","El Registro Electrónico de Pacientes esta disponible en dos ediciones cliente servidor: ",""],
["./role-agregar-o-editar-role.html","Seguridad &#62; Agregar o Editar Role","Los permisos se otorgan o quitan vía los Roles. Los usuarios pueden pertenecer al menos a un role y tendrá los permisos que han sido asignados a l...",""],
["./role-editar-miembros-de-role.html","Seguridad &#62; Editar Miembros de Role","Para agregar, editar o quitar usuarios de un role, es necesario seleccionar y poner en edición el role, de lo contrario no se habilta la edición n...",""],
["./role-editar-permiso-navegacion.html","Seguridad &#62; Editar Permiso de Navegación","Los permisos de navegación son los que permiten o deniegan el acceso a las opciones del árbol de menú a la izquierda en la ventana principal. Para...",""],
["./role-editar-permisos-tipos-bo.html","Seguridad &#62; Editar Permisos para Tipos de Objetos","Los tipos de objetos de negocio corresponden a las tablas en la base de datos. En el componente de seguridad puede definir diferentes políticas a ...",""],
["./role-editar-politica-navegacion.html","Seguridad &#62; Editar Política de Navegación","Las políticas de navegación son las que permiten o deniegan el acceso a las opciones del árbol de menú a la izquierda en la ventana principal. Par...",""],
["./role-usuario.html","Seguridad &#62; Usuario","Esta opción esta disponible para los usuarios que pertenecen al Role con privilegios Administrativos, en nuestro caso el role es Administradores. ...",""],
["./role.html","Seguridad &#62; Role","Esta opción esta disponible para los usuarios que pertenecen al Role con privilegios Administrativos, en nuestro caso el role es Administradores. ...",""],
["./validar-registro.html","Funciones Generales &#62; Validar Registro","Esta función facilita realizar las validaciones de los datos ingresados, a fin de comprobar que cumplen con las reglas establecidas previo a guard...",""],
["./vista-detalle.html","Funciones Generales &#62; Vista Detalle","Cuando da doble clic sobre el registro seleccionado o el botón Editar, se despliega una nueva pestaña con el detalle de ese registro, en la mayorí...",""],
["./vista-lista.html","Funciones Generales &#62; Vista Lista","Siempre que selecciona una opción de Mantenimiento o Consulta, la página que se despliega contiene una lista (grid) con los registros; excepto cua...",""]];
